version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: myapp
    container_name: springboot-app
    build:
      context: ../java
    ports:
      - "8084:8080"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
